title: ますどら
email: buto.takeshi@gmail.com
description: Jekyllで作ったシンプルなブログです。
baseurl: ""
url: "https://mathdrugs.fun"

author:
  name: BUTO Takeshi
  twitter: ButoTakeshi

# フッターに表示する新着記事の本数
footer_recent_posts_limit: 5


# 変換設定
markdown: kramdown
kramdown:
  math_engine: null

permalink: /blog/:year/:month/:day/:title/

# Twitter Cardの設定
twitter:
  username: ButoTakeshi
  card: summary_large_image # 画像を大きく表示する設定

# OGP用のデフォルト画像（画像がない記事の時に使われます）
# assets/images/ogp-default.png などを作成して配置してください
image: /assets/images/top-eyecatch.png

# プラグイン（GitHub Pages標準）
plugins:
  - jekyll-seo-tag
  - jekyll-gist